# Dockerfile (Jenkins 커스텀 이미지)
FROM jenkins/jenkins:lts

USER root
# 도커와 도커 컴포즈 설치 (간단한 예시로 apt-get 이용)
RUN apt-get update && \
    apt-get install -y docker.io docker-compose && \
    rm -rf /var/lib/apt/lists/*

USER jenkins
