services:
  jenkins:
    container_name: jenkins
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    user: root
    ports:
      - "18081:8080"   # Jenkins 웹 UI 접속 포트
      - "50000:50000" # 에이전트 연결 포트
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  jenkins_home:
